package edu.towson.cis.cosc442.project4.coffeemaker;

import org.junit.Test;

import junit.framework.TestCase;

/**
 * The class <code>InventoryTest</code> contains tests for the class {@link
 * <code>Inventory</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 3/26/15 2:33 PM
 *
 * @author User
 *
 * @version $Revision$
 */
public class InventoryTest extends TestCase {
	private CoffeeMaker cm;
	private Inventory i;
	private Recipe r1;

	public void setUp() {
		cm = new CoffeeMaker();
		i = cm.checkInventory();
		
		r1 = new Recipe();
		r1.setName("Coffee");
		r1.setPrice(50);
		r1.setAmtCoffee(20);
		r1.setAmtMilk(1);
		r1.setAmtSugar(1);
		r1.setAmtChocolate(1);
	}
	
	/**
	 * Test setMilk() method to make sure that the value is set to 0 when a negative value is passed.
	 *
	 * @throws Exception the exception
	 */
	@Test
	public void testSetMilk() throws Exception {
		i.setMilk(-2);
		assertEquals(0, i.getMilk());
	}
	
	/**
	 * Test setCoffee() method to make sure that the value is set to 0 when a negative value is passed.
	 *
	 * @throws Exception the exception
	 */
	@Test
	public void testSetCoffee() throws Exception {
		i.setCoffee(-2);
		assertEquals(0, i.getCoffee());
	}
	
	/**
	 * Test setChocolate() method to make sure that the value is set to 0 when a negative value is passed.
	 *
	 * @throws Exception the exception
	 */
	@Test
	public void testSetChocolate() throws Exception {
		i.setChocolate(-2);
		assertEquals(0, i.getChocolate());
	}
	
	/**
	 * Test setSugar() method to make sure that the value is set to 0 when a negative value is passed.
	 *
	 * @throws Exception the exception
	 */
	@Test
	public void testSetSugar() throws Exception {
		i.setSugar(-2);
		assertEquals(0, i.getSugar());
	}
	
	@Test
	public void testEnoughIngredients() throws Exception {
		assertFalse(i.enoughIngredients(r1));
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = edu.towson.cis.cosc442.project4.coffeemaker
 * package.sourceFolder = CoffeeMaker/src
 * superclassType = junit.framework.TestCase
 * testCase = InventoryTest
 * testClassType = Inventory
 */